<<<<<<< HEAD
"use client"; // Asegúrate de incluir esta línea

import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { usePathname } from "next/navigation"; 
import { metadata } from "./metadata"; // Asegúrate de que esta ruta sea correcta
=======
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
>>>>>>> 5ab54bc479f1f03d2f4bb12a0b68cf1f441938a8

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

<<<<<<< HEAD
=======
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

>>>>>>> 5ab54bc479f1f03d2f4bb12a0b68cf1f441938a8
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
<<<<<<< HEAD
  const pathname = usePathname(); // Obtener la ruta actual

  return (
    <html lang="en">
      <head>
        {/* Asegúrate de incluir el uso de metadata aquí */}
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {pathname === "/admin/login" ? null : <Navbar />} {/* Condición para mostrar el Navbar */}
=======
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
>>>>>>> 5ab54bc479f1f03d2f4bb12a0b68cf1f441938a8
        {children}
      </body>
    </html>
  );
}
